ClementLaussucq/hife

- app/controllers/meetings_controller.rb
- app/models/user.rb
- app/views/meetings/create.html.erb
- app/views/meetings/new.html.erb
- config/routes.rb
- test/controllers/meetings_controller_test.rb
Hello guys, our first PR!
@ClementLaussucq can you review my PR as Chris Key du 13 is not registered yet!
- Adding meetings routes + agendas nested routes within meetings (new and create actions only)
- Adding meetings controller (beginning to code the different actions)
- Began the first step with simple_form for the meeting creation to fetch the name of the meeting
> first step of meeting creation - new meeting - name input

- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_hife.scss
- app/assets/stylesheets/components/_index.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/config/_fonts.scss
config colors, fonts, + partials scss
> scssbiatch

- app/controllers/meetings_controller.rb
- app/models/user.rb
- app/views/meetings/new.html.erb
- config/routes.rb
form working on meeting creation with meeting controller action of new and create
@ChrisKey13 
Please take a look
> full form for meeting creation - without flatpickr

- app/assets/stylesheets/components/_hife.scss
- app/assets/stylesheets/config/_colors.scss
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/views/layouts/application.html.erb
- app/views/meetings/new.html.erb
- package.json
- yarn.lock
@ChrisKey13 
Please check that I've added the possibility to create a meeting with a flatpickr date + hours selection.
The hour selection is in 24hours format and goes 5min by 5min. Impossible to seize a meeting starting at 16:42 for example.
> adding flatpickr to meeting creation form

- app/views/pages/home.html.erb
@ChrisKey13 
your Path (homepage) towards new meeting when clicking on "try it free" didn't work. 
I fixed it.
check it please.
> fixed path homepage towards new_meeting

- app/assets/stylesheets/components/_carousel.scss
- app/javascript/components/carousel_slider.js
- app/models/user.rb
- app/views/meetings/new.html.erb
@ChrisKey13 
Pimping the creation form of meetings
Please review
> add html to creation form

- app/assets/stylesheets/components/_carousel.scss
- app/controllers/meetings_controller.rb
- app/javascript/components/banner.js
- app/javascript/components/carousel_slider.js
- app/views/meetings/new.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
@ChrisKey13 
- removed some stuff that was not working or displayed on the home page
- added a transition on meeting form
- made some links between pages to navigate easily in home page and dashboard page
Please review
> debug and transition on meeting form and links to navigate easily

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_hife.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/views/pages/dashboard.html.erb
> Dashboardnew

- app/views/pages/dashboard.html.erb
> change typo in dashboard

- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_hife.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/assets/stylesheets/pages/_home.scss
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
- app/views/pages/home.html.erb
- app/views/shared/_navbar.html.erb
> Stickynavbar

- app/controllers/meetings_controller.rb
- app/views/meetings/new.html.erb
> final debugging

- Gemfile.lock
- app/assets/stylesheets/components/_avatar.scss
- app/assets/stylesheets/components/_hife.scss
- app/assets/stylesheets/pages/_dashboard.scss
- app/controllers/dashboard_controller.rb
- app/views/dashboard/_homedash.html.erb
- app/views/dashboard/_layout.html.erb
- app/views/dashboard/analytics.html.erb
- app/views/dashboard/home.html.erb
- app/views/layouts/application.html.erb
- app/views/pages/dashboard.html.erb
- config/routes.rb
- test/controllers/dashboard_controller_test.rb
> Newdashboard

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/controllers/meetings_controller.rb
- app/javascript/components/carousel_slider.js
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/models/activity.rb
- app/views/meetings/new.html.erb
@ChrisKey13 
Adding map to creation form working with a grid
> add map to creation form

- app/assets/stylesheets/components/_card-activity.scss
- app/javascript/components/carousel_slider.js
- app/javascript/packs/application.js
- app/views/meetings/new.html.erb
@ChrisKey13 
Please review! Works on clik to display each activity; dirty front, need to make it nicer like we said;
Bizu
> slides activities working on click radio button - dirty front

- app/javascript/components/meeting_slider.js
- app/javascript/packs/application.js
@ChrisKey13 
Please ack! It's to avoid having errors in JS console
> fixing some bugs to avoid js errors in console

- app/views/dashboard/_analytics.html.erb
> modifieddashboard

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/controllers/meetings_controller.rb
- app/javascript/components/activity_master.js
- app/javascript/components/activity_picker_slider.js
- app/javascript/components/agenda.js
- app/javascript/components/carousel_slider.js
- app/javascript/components/meeting_slider.js
- app/javascript/packs/application.js
- app/views/meetings/_activities.html.erb
- app/views/meetings/new.html.erb
- config/application.rb
@ChrisKey13 
Unfinished work on the meeting creation
> slider unfinished for meeting creation

- app/javascript/packs/application.js
- app/javascript/plugins/googlecharts.js
- app/views/dashboard/_analytics.html.erb
- app/views/layouts/application.html.erb
> debueug googlechart

- Gemfile
- Gemfile.lock
- app/controllers/meetings_controller.rb
- app/javascript/components/agenda.js
- app/views/meetings/new.html.erb
@ChrisKey13 
Back end works fine for the super feature of meeting creation form
> meeting controller nice and slow

- app/assets/stylesheets/components/_card-activity.scss
- app/javascript/packs/application.js
- app/javascript/plugins/init_mapbox.js
- app/views/meetings/_activities.html.erb
@ChrisKey13 
Adding working map on activities; need to change the design to fit the div and add logo to company marker
> adding map to activities

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_index.scss
- app/javascript/components/agenda.js
- app/javascript/components/meeting_creation.js
- app/javascript/packs/application.js
- app/views/meetings/_activities.html.erb
- app/views/meetings/new.html.erb
@ChrisKey13 
- Activated the security to create a meeting in JS
- Changed the generation of bullet points users to make it automatic which was hard coded in JS (for collaborators in charge)
-  Front design (which needs to be continued) of card activity in the form
Please review and merge!
> Meeting activity front design

- app/assets/stylesheets/components/_card-activity.scss
- app/javascript/plugins/init_mapbox.js
- app/views/meetings/_activities.html.erb
@ChrisKey13 
Yo, now everything's good for the map. Fits the div and logo appears!
> activity map in creation form

- app/assets/stylesheets/pages/_meeting.scss
- app/views/dashboard/_analytics.html.erb
- app/views/meetings/new.html.erb
- db/seeds.rb
@ClementLaussucq  @nicolasmartin86
> dataestablished

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/controllers/meetings_controller.rb
- app/javascript/components/agenda.js
- app/javascript/components/meeting_creation.js
- app/javascript/packs/application.js
- app/javascript/plugins/flatpickr.js
- app/javascript/plugins/init_mapbox.js
- app/javascript/plugins/sweetalert.js
- app/views/meetings/new.html.erb
- package.json
- yarn.lock
@ChrisKey13 
- Adding sweetalert2 to meeting creation form
- Front design of activity sliders at the end of meeting creation
- Some quick cleaning of console.log("toto") in different JS
- Default flatpickr ensuring that you can select a date before today
> Start debug map

- app/javascript/components/meeting_creation.js
@ChrisKey13 
Please merge this one so we can use the form
> debug JS create button enabled

- app/assets/stylesheets/components/_agenda.scss
- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/config/_colors.scss
- app/assets/stylesheets/pages/_meeting.scss
- app/views/meetings/new.html.erb
@ClementLaussucq  @nicolasmartin86
> Newdashboardcss

- app/assets/stylesheets/components/_carousel.scss
- app/views/meetings/new.html.erb
- app/views/pages/home.html.erb
@ChrisKey13 
Please merge for debug
> debug the pages for heroku

- Gemfile.lock
- app/assets/stylesheets/components/_agenda.scss
- app/assets/stylesheets/components/_buttons.scss
- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_hife.scss
- app/assets/stylesheets/components/_navbar.scss
- app/assets/stylesheets/config/_bootstrap_variables.scss
- app/assets/stylesheets/config/_colors.scss
- app/views/layouts/application.html.erb
- app/views/meetings/new.html.erb
> newactivityslider

- app/assets/stylesheets/components/_carousel.scss
- app/controllers/meetings_controller.rb
- app/javascript/plugins/sweetalert.js
- app/views/pages/home.html.erb
@ChrisKey13 
Please merge
- home buttons changed when user signed in to be consistent with the rest
- sweet alert with a message for time saved
> sweet alert and home buttons corrected

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/assets/stylesheets/components/_hife.scss
- app/views/dashboard/_analytics.html.erb
- app/views/meetings/_activities.html.erb
> pushactivity

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_hife.scss
- app/views/meetings/_activities.html.erb
@nicolasmartin86 @ClementLaussucq
> modified activity new

- app/assets/stylesheets/components/_card-activity.scss
- app/assets/stylesheets/components/_carousel.scss
- app/javascript/components/carousel_slider.js
- app/views/meetings/_activities.html.erb
> add js to activity picker and debug

- app/views/dashboard/_navbardash.html.erb
- app/views/meetings/new.html.erb
- app/views/shared/_navbar.html.erb
- db/seeds.rb
> change in navbar creation form to get back to homepage

- app/assets/stylesheets/components/_carousel.scss
- app/views/meetings/new.html.erb
- app/views/shared/_navbar.html.erb
> change little front issue with sliders

- app/assets/stylesheets/components/_carousel.scss
> debug final demo slidebar

- app/assets/stylesheets/components/_carousel.scss
> change sidebar bug
